name: pro_multimedia
description: "Project for Pro Multimedia"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: 9.2.2
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_staggered_grid_view: 0.7.0
  get_it: 7.7.0
  google_fonts: 6.2.1
  injectable: 2.4.4
  intl: 0.19.0
  ionicons: ^0.2.2
  provider: 6.1.2
  video_player: 2.9.1

dev_dependencies:
  auto_route_generator: 9.0.0
  build_runner: 2.4.12
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/files/
    - assets/images/common/
    - assets/images/common/2.0x/
    - assets/images/common/3.0x/


# fvm flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#F9FAFB"
  image: assets/images/common/logo_slaskie.png

  android_12:
    image: assets/images/common/logo_slaskie.png
    color: "#FFFFFF"
    color_dark: "#F9FAFB"
  web: false

# fvm flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/common/logo_white.png"
  remove_alpha_ios: true
  min_sdk_android: 28